// Code generated by parsley-cli; DO NOT EDIT.
//
// This file was automatically generated and any changes to it will be overwritten.

package features

import (
	"github.com/matzefriedrich/parsley/pkg/features"
)

type greeterMock struct {
	features.MockBase
	SayHelloFunc   Greeter_SayHelloFunc
	SayNothingFunc Greeter_SayNothingFunc
}

type Greeter_SayHelloFunc func(name string, polite bool) (string, error)
type Greeter_SayNothingFunc func()

const (
	Function_Greeter_SayHello   = "SayHello"
	Function_Greeter_SayNothing = "SayNothing"
)

func (m *greeterMock) SayHello(name string, polite bool) (string, error) {
	m.TraceMethodCall(Function_Greeter_SayHello, name, polite)
	return m.SayHelloFunc(name, polite)
}

func (m *greeterMock) SayNothing() {
	m.TraceMethodCall(Function_Greeter_SayNothing)
	m.SayNothingFunc()
}

var _ Greeter = (*greeterMock)(nil)

// NewGreeterMock Creates a new configurable greeterMock object.
func NewGreeterMock() *greeterMock {
	mock := &greeterMock{
		MockBase: features.NewMockBase(),
		SayHelloFunc: func(name string, polite bool) (string, error) {
			var result0 string
			var result1 error
			return result0, result1
		},
		SayNothingFunc: func() {},
	}
	mock.AddFunction(Function_Greeter_SayHello, "SayHello(name string, polite bool) (string, error)")
	mock.AddFunction(Function_Greeter_SayNothing, "SayNothing()")
	return mock
}
